### ISSUE TITLE
Problem finding candidates in tables under headings when both org-indent-mode and visual-line-mode are enabled

### ISSUE THREAD

**Issue by phmcc** [shankar2k/company-org-table#2]
First off, great package.  This speeds up my workflow and really enhances the usability of `org` tables.

I've noticed that—for some reason—whenever I have a table under a heading while `org-indent-mode` and `visual-line-mode` are enabled, `company` is unable to find completions using the `company-org-table` backend.  I've tested it out in an `emacs -Q` session, and the behavior is pretty consistent:

- `org-indent-mode` OFF, `visual-line-mode` OFF, table not under header --> WORKS
- `org-indent-mode` OFF, `visual-line-mode` OFF, table under header --> WORKS
- `org-indent-mode` ON, `visual-line-mode` OFF, table not under header --> WORKS
- `org-indent-mode` ON, `visual-line-mode` OFF, table under header --> WORKS
- `org-indent-mode` OFF, `visual-line-mode` ON, table not under header --> WORKS
- `org-indent-mode` OFF, `visual-line-mode` ON, table under header --> WORKS
- `org-indent-mode` ON, `visual-line-mode` ON, table not under header --> WORKS
- `org-indent-mode` ON, `visual-line-mode` ON, table under header --> FAILS

I'm thinking this has something to do with how the regex is searched for completions?  Is there any way to fix this?

**Comment by shankar2k** [comment]
Thank you for the detailed bug report! I tried this out myself and verified that it does indeed require all three conditions for company-org-table to fail. I also observed that `company` works normally in an org file if `company-org-table` is not enabled.

I'm yet not sure where the problem lies. I traced through the execution of `company-org-table-prefix` using `edebug` and verified that it is returning the correct value in all cases.  I tried to similarly trace through `company-org-table-candidates`, but that doesn't get invoked in this situation. I will keep digging to see if I can figure out what's wrong.

**Comment by shankar2k** [comment]
I believe I have figured it out. I was using `goal-column` to efficiently keep the point in the current table column, but apparently that does not play well with `visual-line-mode`. I fixed this issue and tested it with the following test file:
[cot-oim-vlm-bug.org.txt](https://github.com/shankar2k/company-org-table/files/12844042/cot-oim-vlm-bug.org.txt). You will either have to remove the `.txt` extension or invoke `org-mode` manually.

Please update to the latest version of `company-org-table` and let me know if this test file works for you.

**Comment by phmcc** [comment]
Yes—can confirm that this works!  Nicely done.  Thank you.
